set (AUDIORESOURCE_INCLUDE_PATH "/usr/include/audioresource")
set (AUDIORESOURCE_LIBRARY "/usr/lib/libaudioresource.so")

FIND_PACKAGE_HANDLE_STANDARD_ARGS(AUDIORESOURCE AUDIORESOURCE_LIBRARY AUDIORESOURCE_INCLUDE_PATH)
